### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by GrimReaper2654** [the-oom-town/town-interactive#9]
We should create a discord server so we can collaborate easily and have better communication.

**Comment by tvdk-sudoku** [comment]
Or maybe we can invite you to the town discord and just create a channel on there
________________________________
From: Choyu ***@***.***>
Sent: Friday, 5 May 2023 2:40 PM
To: the-oom-town/town-interactive ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [the-oom-town/town-interactive] Discord Server (Issue #9)


We should create a discord server so we can collaborate easily and have better communication.

**Comment by GrimReaper2654** [comment]
sure that works

**Comment by tvdk-sudoku** [comment]
Check your emails

Yours sincerely,
Taj
________________________________
